<a href="https://colab.research.google.com/github/Gagan-poojari/LedgerFlow/blob/main/cX_pytorch_vid4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Training Pipeline

In [52]:
import torch
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [53]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [54]:
df.shape

(569, 33)

In [55]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


Train Test Split

In [56]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

Scaling (uniform data)

In [57]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [58]:
X_train

array([[-0.1022571 , -0.82360659, -0.07132179, ...,  0.36401526,
        -0.47731437,  1.05987493],
       [ 1.68870965,  1.06717873,  1.75907563, ...,  1.18079604,
         0.6181867 ,  0.61059322],
       [ 0.10844487,  1.92939558,  0.18915944, ...,  0.86164651,
         2.05399235,  2.74130227],
       ...,
       [ 0.12552881,  0.93362884,  0.07504385, ...,  0.32771389,
        -0.65135141, -0.81294317],
       [-0.86249259, -0.6291392 , -0.89659245, ..., -1.11617302,
        -0.79741822, -0.67940216],
       [-0.78276752, -1.0274459 , -0.770073  , ..., -0.77554519,
        -1.68625029, -0.49341791]])

Label encoding (for target labels)

In [59]:
y_train

,diagnosis
73,M
302,M
15,M
371,B
154,B
...,...
158,B
92,B
385,M
428,B


In [60]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [61]:
y_train

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,

Converting NumPy arrays to PyTorch tensors

In [62]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [63]:
X_train_tensor, X_train_tensor.shape

(tensor([[-0.1023, -0.8236, -0.0713,  ...,  0.3640, -0.4773,  1.0599],
         [ 1.6887,  1.0672,  1.7591,  ...,  1.1808,  0.6182,  0.6106],
         [ 0.1084,  1.9294,  0.1892,  ...,  0.8616,  2.0540,  2.7413],
         ...,
         [ 0.1255,  0.9336,  0.0750,  ...,  0.3277, -0.6514, -0.8129],
         [-0.8625, -0.6291, -0.8966,  ..., -1.1162, -0.7974, -0.6794],
         [-0.7828, -1.0274, -0.7701,  ..., -0.7755, -1.6863, -0.4934]],
        dtype=torch.float64),
 torch.Size([455, 30]))

# Defining the Model

note: OOP is gon be used a lot while constructing NNs

In [68]:
class NeuralNetwork:
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True) #X.shape[1] gives the no of features corresponding to which we initialize the weights
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True) # a single bias corresponding to the single neuron

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # clamp prediction to avoid log(0)
    epsilion = 1e-7
    y_pred = torch.clamp(y_pred, epsilion, 1 - epsilion)

    # calculate loss (binary cross-entropy loss)
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

Hyperparameters

In [89]:
learning_rate = 0.1
epochs = 100

# Training Pipeline

In [90]:
# 1. create the model
model = NeuralNetwork(X_train_tensor)

# 2. Define loop
for epoch in range(epochs):

  # 2.2 forward pass
  y_pred = model.forward(X_train_tensor)

  # 2.3 loss calculation
  loss = model.loss_function(y_pred, y_train_tensor)

  # 2.4 backward propogation
  loss.backward()

  # 2.5. update parameters (gradient descent)
  with torch.no_grad(): # imp: we wanna perform these two operations without being tracked by the autograd (computational graph)
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # to prevent piliong up of gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()
  if not (epoch + 1) % 10:
    print(f'Epoch: {epoch + 1} -> Loss: {loss.item()}')


Epoch: 10 -> Loss: 3.2633287037686247
Epoch: 20 -> Loss: 1.7364537823150157
Epoch: 30 -> Loss: 0.910949090938773
Epoch: 40 -> Loss: 0.7620072563356676
Epoch: 50 -> Loss: 0.7093443648471749
Epoch: 60 -> Loss: 0.6891244104575313
Epoch: 70 -> Loss: 0.6807755112434103
Epoch: 80 -> Loss: 0.6767186572263888
Epoch: 90 -> Loss: 0.674356851255149
Epoch: 100 -> Loss: 0.6727691057695392


In [91]:
model.weights, model.bias

(tensor([[ 0.1954],
         [-0.1569],
         [-0.1354],
         [-0.4648],
         [ 0.3417],
         [ 0.1662],
         [-0.3773],
         [-0.4403],
         [ 0.1986],
         [-0.1057],
         [-0.2255],
         [ 0.1246],
         [ 0.0585],
         [ 0.0394],
         [ 0.2588],
         [-0.1787],
         [ 0.2064],
         [-0.1576],
         [-0.1553],
         [ 0.1831],
         [ 0.1279],
         [ 0.0956],
         [ 0.3752],
         [ 0.3318],
         [-0.3793],
         [ 0.0832],
         [ 0.1925],
         [ 0.1850],
         [-0.0231],
         [-0.1225]], dtype=torch.float64, requires_grad=True),
 tensor([-0.4554], dtype=torch.float64, requires_grad=True))

Evaluation

In [92]:
with torch.no_grad():
  # test on test data
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float() # 0 / 1

  # compute accuracy
  accuracy = (y_pred == y_test_tensor).float().mean()
print(f'Accuracy: {accuracy.item()}')

# print(y_pred)

Accuracy: 0.6131117343902588
